version: 2.1

orbs:
  node: circleci/node@7.1.0

commands:
  setup:
    steps:
      - checkout

  login:
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

executors:
  node-executor:
    docker:
      - image: cimg/node:22.14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: pnpm
          cache-path: node_modules
          override-ci-command: pnpm install
      - run:
          name: Build
          command: pnpm build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - node/install-packages:
          pkg-manager: pnpm
          cache-path: node_modules
          override-ci-command: pnpm install
      - run:
          name: Run Tests
          command: pnpm test:run

  lint:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - node/install-packages:
          pkg-manager: pnpm
          cache-path: node_modules
          override-ci-command: pnpm install
      - run:
          name: Run Linting
          command: pnpm lint
      - run:
          name: Type Check
          command: pnpm typecheck

  publish-release:
    executor: node-executor
    steps:
      - setup
      - node/install-packages:
          pkg-manager: pnpm
          cache-path: node_modules
          override-ci-command: pnpm install
      - attach_workspace:
          at: .
      - login
      - run:
          name: Publish npm Package
          command: |
            name="$(jq --raw-output .name package.json)"
            version="$(jq --raw-output .version package.json)"
            full_identifier="$name@$version"
            echo "Checking for published version..."
            if [ $(pnpm view $full_identifier --json 2>&1 | jq -s '.[0].type == "error" or .[0].data.dist == null') == "true" ]
            then
              echo "Publishing $full_identifier…"
              pnpm publish --no-git-checks
            else
              echo "$full_identifier already published. Doing nothing."
            fi

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
      - publish-release:
          context: npm-registry-public
          filters:
            branches:
              only: main
          requires:
            - build
            - lint
            - test
