import { z } from 'zod';

export const downloadUsageApiDataInputSchema = z.object({
  orgId: z.string().describe('The ID of the CircleCI organization'),
  startDate: z
    .string()
    .optional()
    .describe('Optional. The start date for the usage data in YYYY-MM-DD format (or natural language). Used when starting a new export job.'),
  endDate: z
    .string()
    .optional()
    .describe('Optional. The end date for the usage data in YYYY-MM-DD format (or natural language). Used when starting a new export job.'),
  jobId: z
    .string()
    .optional()
    .describe('Generated by the initial tool call when starting the usage export job. Required for subsequent tool calls.'),
  outputDir: z
    .string()
    .describe('The directory to save the downloaded usage data CSV file.'),
});
