import { z } from 'zod';

export const downloadUsageApiDataInputSchema = z.object({
  orgId: z.string().describe('The ID of the CircleCI organization'),
  startDate: z
    .string()
    .describe('The start date for the usage data in YYYY-MM-DD format. Time is optional and defaults T00:00:00Z'),
  endDate: z
    .string()
    .describe('The end date for the usage data in YYYY-MM-DD format. It must be within 32 days of the start date. Time is optional and defaults T23:59:59Z'),
  jobId: z
    .string()
    .optional()
    .describe('Generated by the initial tool call when starting the usage export job. Required for subsequent tool calls.'),
  outputDir: z
    .string()
    .describe('The directory to save the downloaded usage data CSV file.'),
});
