import { listArtifactsInputSchema } from './inputSchema.js';
import { option1DescriptionBranchRequired } from '../shared/constants.js';

export const listArtifactsTool = {
  name: 'list_artifacts' as const,
  description: `
    This tool retrieves the list of artifacts produced by a CircleCI job.

    Common use cases:
    - List all artifacts generated by a specific job
    - Find download URLs for build artifacts (binaries, reports, logs, etc.)
    - Check what artifacts were produced by a pipeline run

    Input options (EXACTLY ONE of these THREE options must be used):

    ${option1DescriptionBranchRequired}

    Option 2 - Direct URL (provide ONE of these):
    - projectURL: The URL of the CircleCI job in any of these formats:
      * Job URL: https://app.circleci.com/pipelines/gh/organization/project/123/workflows/abc-def/jobs/789
      * Workflow URL: https://app.circleci.com/pipelines/gh/organization/project/123/workflows/abc-def
      * Pipeline URL: https://app.circleci.com/pipelines/gh/organization/project/123

    Option 3 - Project Detection (ALL of these must be provided together):
    - workspaceRoot: The absolute path to the workspace root
    - gitRemoteURL: The URL of the git remote repository
    - branch: The name of the current branch

    Additional Requirements:
    - Never call this tool with incomplete parameters
    - If using Option 1, make sure to extract the projectSlug exactly as provided by listFollowedProjects and include the branch parameter
    - If using Option 2, the URL MUST be provided by the user - do not attempt to construct or guess URLs
    - If using Option 3, ALL THREE parameters (workspaceRoot, gitRemoteURL, branch) must be provided
    - If none of the options can be fully satisfied, ask the user for the missing information before making the tool call
    `,
  inputSchema: listArtifactsInputSchema,
};
